default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: scrbabble_development

test:
  <<: *default
  database: scrbabble_test

production:
  <<: *default
  database: scrbabble_production
